name: Docusarus Deploy

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Base Repo
        uses: actions/checkout@v3

      - name: PNPM Initialization
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm' 
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build Website
        run: pnpm build

      - name: Deployment to Github Pages Workflow 
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true